name: Add Or Remove Labels
description: Add or remove labels on PRs or issues

author: Okinea Dev

inputs:
  labels:
    description: A comma-separated list of labels
    type: string
    required: true
  action:
    description: "`add` or `remove` label"
    type: string
    default: add
    required: false

runs:
  using: composite
  steps:
    - name: 🔖 Add or remove labels
      shell: bash
      env:
        ISSUE_NUMBER: ${{ github.event.number }}
        ACTION: ${{ inputs.action }}
        LABELS: ${{ inputs.labels }}
      run: $GITHUB_ACTION_PATH/add-or-remove-labels.sh "$ISSUE_NUMBER" "$ACTION" "$LABELS"
branding:
  icon: tag # 🏷️
  color: yellow # 🟡
